### ISSUE TITLE
Consent flow not working

### ISSUE THREAD

**Issue by chippiearnold** [AzureADSamples/NativeClient-WebAPI-MultiTenant-WindowsStore#3]
I have configured the sample within my default directory, then created a new Directory for testing the onboarding process for multi-tenants. When I try to sign up with an account from the second test directory, after entering the credentials in the Azure login screen, I do not get the consent flow. Instead, the AuthenticationResult is in an error state of "ACCESS_DENIED" with the following description:

AADSTS65005: The application needs access to a service that your organization xxx has not subscribed to. Please contact your Administrator to review the configuration of your service subscriptions.
Trace ID: 82d8da08-76c0-4e2d-892d-4fcc20326564
Correlation ID: 6de18877-e33c-4e26-8e89-b4bc86bb9394
Timestamp: 2015-04-22 11:07:22Z

I have tried with both user and admin accounts from the test directory - all result in the same message.

If I sign up with an account from the default tenant (where the app and API is provisioned) then everything works as it should.

To confirm, the application has the "is multitenanted" option set to "YES".

**Comment by chippiearnold** [comment]
Just to update, I have found the issue. When I edited the manifest to add the "Known client applications" entry (as per step 4) it seems that the edits I made were not persisted when I re-uploaded the manifest. I re-downloaded it to check and the entry I made was not there. I redid this step and this time the edit was there, and I am now seeing the consent flow as expected.

**Comment by dstrockis** [comment]
Great! Thanks for closing.
